spring:
  application:
    name: DatabaseMeta
  datasource:
    url: jdbc:postgresql://190.211.1.250:5432/watererp
    username: ruis
    password: ruis@2026
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10